services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
  # usuario: cleriston / senha: 123456

  sonarqube:
    container_name: sonar
    image: sonarqube:lts-community
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://pg-sonar:5432/sonar
    depends_on:
      - pg-sonar
  pg-sonar:
    container_name: pg-sonar
    image: postgres:9.6
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

networks:
  sonarnet:
    driver: bridge
